<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Prasanna" failures="1" tests="3" name="com.zenken.freshers.user.Projects" time="147.683" errors="0" timestamp="2024-11-22T16:02:15 IST" skipped="2">
  <testcase classname="com.zenken.freshers.user.Projects" name="verifyProjectAdditionWithFile" time="47.650">
    <failure message="expected [Sample_Project.pdf] but found [Sample_Project (3).pdf]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Sample_Project.pdf] but found [Sample_Project (3).pdf]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.zenken.freshers.user.Projects.verifyProjectAdditionWithFile(Projects.java:233)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- verifyProjectAdditionWithFile -->
  <testcase classname="com.zenken.freshers.user.Projects" name="verifyProjectAdditionWithFile" time="52.815">
    <skipped/>
  </testcase> <!-- verifyProjectAdditionWithFile -->
  <testcase classname="com.zenken.freshers.user.Projects" name="verifyProjectAdditionWithFile" time="47.218">
    <skipped/>
  </testcase> <!-- verifyProjectAdditionWithFile -->
</testsuite> <!-- com.zenken.freshers.user.Projects -->
